os:
  - 'linux'
  - 'osx'
  - 'windows'
sudo: false

language: 'go'
go:
  - '1.10'
  - '1.11'

install:
  - 'cd $GOPATH'
  - 'if [ "$(go version | awk ''{print $3}'')" == "go1.10" ]; then go get -u golang.org/x/vgo && BIN=vgo; else BIN=go; fi'
  - 'mv ${TRAVIS_BUILD_DIR} ${TRAVIS_HOME}/test'
  - 'cd ${TRAVIS_HOME}/test'
script: '${BIN} test -v -race -count=10'
